# Generated by Django 6.0.6 on 2026-07-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='materiaAsignada',
            field=models.CharField(default='Sin asignar', max_length=100),
            preserve_default=False,
        ),
    ]
