# Generated by Django 6.0.6 on 2026-09-28 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_curso_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='materiaAsignada',
        ),
        migrations.AddField(
            model_name='profesor',
            name='curso_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.curso', verbose_name='Curso Asignado'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='profesion',
            field=models.CharField(choices=[('Profesor', 'Profesor'), ('Profesora', 'Profesora')], default='Profesor', max_length=20, verbose_name='Título / Rol'),
        ),
    ]
