# Generated by Django 6.0.6 on 2026-09-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_profesor_materiaasignada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Curso Activo?'),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización'),
        ),
    ]
