# Generated by Django 6.0.6 on 2026-09-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_curso_activo_curso_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
    ]
