# Generated by Django 6.0.6 on 2026-09-29 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_curso_fecha_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregable',
            name='fecha_entrega',
        ),
        migrations.AddField(
            model_name='entregable',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='myapp.curso', verbose_name='Curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entregable',
            name='estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='myapp.estudiante', verbose_name='Estudiante Asignado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entregable',
            name='fecha_inicio',
            field=models.DateField(default='2026-01-01', verbose_name='Fecha de Inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entregable',
            name='nota',
            field=models.FloatField(blank=True, null=True, verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='entregable',
            name='entregado',
            field=models.BooleanField(default=False, verbose_name='¿Fue entregado?'),
        ),
        migrations.AlterField(
            model_name='entregable',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre del Trabajo'),
        ),
    ]
