# Generated by Django 6.0.6 on 2026-09-29 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_entregable_fecha_entrega_entregable_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoPractico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título del Trabajo Práctico')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Consigna / Descripción')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha Límite de Entrega')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_practicos', to='myapp.curso', verbose_name='Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='entregas_archivos/', verbose_name='Archivo Adjunto')),
                ('fecha_subida', models.DateTimeField(auto_now=True)),
                ('entregado', models.BooleanField(default=False, verbose_name='¿Entregado?')),
                ('nota', models.FloatField(blank=True, null=True, verbose_name='Calificación')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='myapp.estudiante')),
                ('trabajo_practico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='myapp.trabajopractico')),
            ],
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
    ]
