# Generated by Django 6.0.6 on 2026-09-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_trabajopractico_entrega_delete_entregable'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='password_curso',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contraseña del curso'),
        ),
    ]
