# Generated by Django 6.0.6 on 2026-09-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('profesor', 'Profesor'), ('alumno', 'Alumno')], default='alumno', max_length=20),
        ),
    ]
